- main.go
Include a command line arg to customize the ProduceBatchMaxBytes parameter.
> main: add batchMaxBytes command line arg

- main.go
Added a validating read mode where a bunch of fibers is started and they then join a single consumer group and read and validate all messages from a topic in parallel.
> Add consumer group reader

- main.go
It'd be useful to know the error returned by kgo on produce failures when debugging CI failures.
Related to https://github.com/redpanda-data/redpanda/issues/4761
> Log error for produce failures

- Dockerfile
This PR adds a simple Dockerfile that builds `kgo-verifier`. I wrote it for myself in order
to attach `kgo-verifier` pods to a running Kubernetes cluster. Maybe someone else would find it useful.
It would also simplify our internal instructions for creating the set-up I described (currently this code lives
in a gist).
> Add a simple Dockerfile

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
- pkg/worker/repeater/repeater_worker.go
- pkg/worker/transaction_stm.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/seq_read_worker.go
Adds a transactional producer that produces messages in transactions. 
Questions:
- Should this be it's own producer as it is implemented here or should the existing producer should be modified to support transactions?
- Do we want a producer that can interleave transactions and regularly produced messages?
> Add support for verifying transactions

- go.mod
- go.sum
- pkg/worker/verifier/seq_read_worker.go
From debugging of https://github.com/redpanda-data/redpanda/issues/7231 where noise from defunct clients was quite noticeable on the server side.
> kgo-verifier: explicitly close client in seq_consumer

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
- pkg/worker/repeater/repeater_worker.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/seq_read_worker.go
- pkg/worker/worker.go
Two issues seen:
- Producer writes out fragmented valid_offsets file when doing transactional production, because the control offsets aren't in the valid range.
- Consumer is not properly configured, it did not have the options to read only committed, and it _did_ have the option for reading control batches, but wasn't skipping them.
This should now work reliably for verifying a produce/consume cycle on a single partition.
The existing code was not safe for multiple partitions: it assumes that each partition start/end writes a control batch to every partition, but that is only true if the producer had written to all the partitions.  Needs further improvement.
> kgo-verifier: improve transaction verification

- pkg/worker/verifier/producer_worker.go
On "unexpected offsets" conditions, the producer
will drop out of produceInner and re-enter, to
destroy and create a client.
However, dropping the reference to the client doesn't synchronously close it, so it's possible for the
client to remain alive too long, and perhaps continue to drain its produce channel, disrupting the offset checks in the subsequent call to produceInner.
It's not certain that we've seen this happen, but it is one possibility discussed in https://github.com/redpanda-data/redpanda/issues/8289 that is straightforward to eliminate.
Related: https://github.com/redpanda-data/redpanda/issues/8289
> kgo-verifier: close client in produceInner

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
This was previously only printing the stack of the current goroutine.
The /print_stack endpoint enables tests to trigger a stack dump when they can detet that something has gone wrong other than a hang, such as when a consumer mysteriously drops out of a consumer group.
> Fix stack trace print + add explicit /print_stack endpoint

- cmd/kgo-verifier/main.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/validator_status.go
Added support for compacted topics in a verifier. Change the way how record identifiers are stored. This allowed to use an arbitrary value as a record key. Added command line option to generate record keys from a set of a specified cardinality.
> Compacted topics support

- pkg/worker/repeater/repeater_worker.go
Previously we were taking our `sentAt` timestamp before waiting on the rate limiter.
> kgo-repeater: don't include rate limiting in latency stat

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
This should get us all the goroutines, not just
a subset.
> Use debug=2 for pprof goroutine dumps

- README.md
- cmd/kgo-verifier/main.go
- pkg/worker/worker.go
Utilized the TLS dialer to enable TLS support for kgo-verifier. Caveat: Must use a 'known' CA to sign certificates, or add your CA to the OS's list of good CAs.
> kgo-verifier: Enabled support for TLS

- pkg/worker/repeater/repeater_worker.go
ProducerBatchCompression is provided by the worker config but was being overridden to NoCompression.  Remove that line
> worker/repeater: Remove override of compression

- pkg/worker/repeater/repeater_worker.go
- pkg/worker/verifier/group_read_worker.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/random_read_worker.go
- pkg/worker/verifier/seq_read_worker.go
This change was prompted by testing on the LRC.  We have multiple instances of kgo* running, so in order to keep track of which topic, I added the topic name to the status structures.
> status: Added topic name to status

- cmd/kgo-verifier/main.go
- pkg/worker/verifier/group_read_worker.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/random_read_worker.go
- pkg/worker/verifier/seq_read_worker.go
- pkg/worker/verifier/validator_status.go
- pkg/worker/worker.go
This PR does two things:
1. Fix races on accessing the HWM maps in the worker status
2. Make the timestamp step configurable when producing with custom timestamps
> kgo-verifier: fix status map race and make timestamp step configurable

- go.mod
Discovered that this requires 1.19 to build now. So the mod file should indicate that.
> kgo-verifier: require go 1.19

- cmd/kgo-verifier/main.go
- pkg/worker/verifier/producer_worker.go
Added ability to recreate a producer client every specified number of messages. Recreation of producer forces creation of new unique producer id. This setup allow to stress Redpanda producer id cache implementation as it generates lots of unique producer ids.
> producer: added ability to recreate producer after given number of msgs

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
Due to test infra issues we've had these services started where previous instances were already running leading to very hard to debug results.
Panic right away instead of silently ignoring the error.
I'm choosing to do it in the most simple way as a graceful server shutdown is not required for the use-cases on these services.
Before:
```
→ ./kgo-verifier -topic aba -debug -produce_msgs 10
INFO[0000] Getting topic metadata...
DEBU[0000] Targeting topic aba with 1 partitions
INFO[0000] Starting producer...
...
DEBU[0000] Writing partition 0 at 50
...
INFO[0000] Finished producer.
```
After:
```
→ ./kgo-verifier -topic aba -debug -produce_msgs 10
INFO[0000] Getting topic metadata...
DEBU[0000] Targeting topic aba with 1 partitions
INFO[0000] Starting producer...
INFO[0000] Loading offsets …
```
> panic if the listener for remote control can not be started

- cmd/kgo-repeater/main.go
- pkg/worker/repeater/repeater_worker.go
There is a need for the kgo-repeater to distribute its load across topics & partitions, not just the many partitions of one topic. This PR adds the logic to do this, the list of topics is passed as a comma delimited string and the producers will choose one of those topics at random to produce to. Consumers will pass the entire list to their subscribe call.
> Make the kgo-repeater multi-topic aware

- cmd/kgo-verifier/main.go
This is being invoked by stress tests which run consumers in a loop but want to ensure at the end that all the data was read.
kgo first requests high topic watermark, then starts routines that read up to that watermark. If the last run begins before all the data is written, then `/last_pass` is called, it will exit without having a chance to read all the data.
This is for https://github.com/redpanda-data/redpanda/issues/12109
> kgo: run one extra pass after /last_pass request

- cmd/kgo-verifier/main.go
Previously the code didn't wait for `/last_pass` request before stopping the consumer.
> verifier: fixed stopping consumers when loop is requested

- .github/workflows/go.yml
- .gitignore
- Makefile
- cmd/kgo-verifier/main.go
- pkg/util/util.go
- pkg/util/util_test.go
- pkg/worker/repeater/repeater_worker.go
- pkg/worker/verifier/group_read_worker.go
- pkg/worker/verifier/offset_ranges.go
- pkg/worker/verifier/offset_ranges_test.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/seq_read_worker.go
- pkg/worker/verifier/validator_status.go
- pkg/worker/worker.go
* Introduce a `-continuous` flag which instructs kgo-verifier to continue polling for new data rather than exiting or looping.
* Introduce a `-tolerate-data-loss` flag which facilitates testing write caching feature where data loss is tolerable in specific circumstances.
> verifier: tolerate data loss

- go.mod
- pkg/worker/verifier/validator_status.go
- pkg/worker/verifier/validator_status_test.go
To catch bugs like https://github.com/redpanda-data/redpanda/pull/23835
> record all records and validate leader epoch monotonicity

- pkg/worker/verifier/client_helpers.go
If the number of partitions is high and leadership transfers happen often we may be unable to get a single all-successful result for a long time. Instead, combine a full result out of tolerate partially successful ones.
> consumer: combine offset map from multiple partially successful replies

- cmd/kgo-repeater/main.go
- cmd/kgo-verifier/main.go
- pkg/worker/repeater/repeater_worker.go
- pkg/worker/verifier/group_read_worker.go
- pkg/worker/verifier/latest_value_map.go
- pkg/worker/verifier/offset_ranges.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/random_read_worker.go
- pkg/worker/verifier/seq_read_worker.go
- pkg/worker/verifier/validator_status.go
- pkg/worker/verifier/validator_status_test.go
- pkg/worker/worker.go
Adds new flags and validation enhancements to `kgo-verifier`:
`--tombstone-probability`, which allows for random production of tombstone records per the input parameter.
`--compacted`, which indicates that the topic to be verified is compacted. A warning about gaps in consumed offsets will not be shown if this is `true`
`--validateLatestValues`, which if true, performs verification of the consumed keys against the latest values produced by a worker. The log should be fully compacted before the consumer is started if this flag is passed as `true`.
> Compaction verification enhancements

- pkg/worker/verifier/latest_value_map.go
- pkg/worker/verifier/offset_ranges.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/verifier/validator_status.go
This didn't account for tombstones being produced for the same key later in the log.
Fix the logic by adding a new `latestKoByPartition` map which tracks the last offset for a given key. By using it in combination with `latestKvByPartition`, we can conclude which non-tombstone record/key has the highest offset for a given partition.
> `verifier`: fix `lastConsumableOffsets`

- cmd/kgo-repeater/main.go
Listen for SIGTERM and call all Shutdown() in the verifiers.
See commits and CORE-8470 for additional context.
> Repeater should leave CG on graceful shutdown

- pkg/worker/verifier/producer_worker.go
[Using the modified `ValueGenerator::Generate()` function for each record in the `producer_worker`](https://github.com/redpanda-data/kgo-verifier/pull/60#discussion_r1842693465) was a lot slower than just simply making an empty payload.
The following benchmarks were generated:
```
Benchmark_random_payload10-32           	 2445903	        485.2 ns/op
Benchmark_random_payload100-32           	  678870	         1773 ns/op
Benchmark_random_payload1000-32           	  105667	        13700 ns/op
Benchmark_random_payload1e4-32          	    9104	       126782 ns/op
Benchmark_random_payload1e5-32          	    1135	      1151425 ns/op
Benchmark_random_payload1e6-32          	     100	     13046547 ns/op
==================================================================================== …
```
> `producer_worker`: revert use of `ValueGenerator::Generate()`

- pkg/worker/verifier/group_read_worker.go
- pkg/worker/verifier/seq_read_worker.go
crash instantly on data loss errors
We (@nvartolomei and @bash) found that GroupReadWorker wouldn't report
data loss. The reason is that we didn't fail the test instantly when
data loss is detected instead we relied on monotonicity validation to
fail. I.e. we would crash when we detected that we would consume an
earlier offset compared to what we consumed before.
In the GroupReadWorker we reset the monotonicity validation state on any
errors because the next attempt at consuming is almost certain to read
the second time offsets already consumed. As a result we wouldn't catch
monotonicity issues.
In retrospect, it would have been better to fail instantly when franz-go
detects data loss. So this commit achieves exactly that.
> crash instantly on data loss errors

- cmd/kgo-verifier/main.go
- pkg/worker/verifier/producer_worker.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
Currently unless we are in latest offset verifier mode, we only append zeros which is very compressible. Too compressible.
> Random data produce

- cmd/kgo-verifier/main.go
Also return an error on the status endpoint if workers are not fully registered yet. Our callers expect that there is always at least one worker report on the status endpoint.
> fix race condition when /status is polled before workers are registered
